/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import Clientes.clientes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class FormFechaVenda extends javax.swing.JDialog {

    /**
     * Creates new form FormFechaVenda
     */
    public FormFechaVenda() {
        initComponents();
    }
    
    private final String numeros = "0123456789.";
    private final DecimalFormat decimal = new DecimalFormat("0.00");
    private final DateFormat DATA = new SimpleDateFormat("yyyy-MM-dd");
    private Date data;
    private ClasseVendaMesa vendaMesa;
    private DefaultTableModel itensMesa;
    private TelaMesa telaPai;
    private clientes tbClientes = new clientes();
   

    public void setTelaPai(TelaMesa telaPai) {
        this.telaPai = telaPai;
    }
    
    //seta os valores iniciais dos textboxs
    public void valores(String numMesa,String valorD,DefaultTableModel itens){
        valorD = valorD.replaceAll(",",".");
        lbNumMesa.setText(numMesa);
        txtSubTotal.setText(valorD);
        txtTaxaServico.setText(decimal.format(Float.valueOf(valorD)*0.10).replaceAll(",", "."));
        txtValorPagar.setText(String.valueOf(Float.valueOf(valorD)+Float.valueOf(txtTaxaServico.getText())));
        itensMesa = itens;
        if(cmbFormaPagamento.getSelectedItem().equals("A PRAZO")){
                btPesquisaCliente.setEnabled(true);
                jTNomeCliente.setVisible(true);
        }
    }

    //calcula o valor da compra automaticamente.
    public void calculaVPagar() {
        //Converto os valores e salvo em variaveis para não me perder no codigo
        float troco = (Float.valueOf(txtValorRecebido.getText()) - Float.valueOf(txtValorPagar.getText()));
        float taxa = Float.valueOf(txtTaxaServico.getText());
        //Pega o valor do desconto.
        float desc;
        if (txtDesconto.getText().equals("") || txtDesconto.getText().equals(",")) {
            desc = 0;
        } else {
            desc = Float.valueOf(txtDesconto.getText());
        }
        
        float Valorp = (Float.valueOf(txtSubTotal.getText())+taxa)-desc;
        float ValorR = Float.valueOf(txtValorRecebido.getText());
        
        //verifica forma de pagamento  e aplica a melhor opção para o mesmo.
        if (cmbFormaPagamento.getSelectedIndex() != -1) {
            if (cmbFormaPagamento.getSelectedItem().equals("DINHEIRO")) {
                
                txtValorPagar.setText(String.valueOf(Valorp));
                if (troco >= 0) {
                    txtTroco.setText(decimal.format(troco).replaceAll(",","."));
                } else {
                    txtTroco.setText("0.00");
                }
            } else if (Valorp >= ValorR) {
                txtValorPagar.setText(decimal.format(Valorp).replaceAll(",","."));
                txtTroco.setText("0.00");
  
            }else {
                JOptionPane.showMessageDialog(this, "Impossivel Debitar valor maior\nque o valor devido!",
                        "Fechamento da Venda", JOptionPane.INFORMATION_MESSAGE);
                txtValorRecebido.setText("0.00");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma Forma de\nPagamento!",
                    "Fechamento de Venda", JOptionPane.INFORMATION_MESSAGE);
            
        }

    }
    
    //retorna a data formatada para salvar no banco de dados
    public String retornaData(){
        data = new Date();
        String aux = DATA.format(data);
        return aux;
    }
    
    //preenche os dados da compra na classe para salvar no banco de dados
    public void preencheClasse(){
        if (vendaMesa == null){
            vendaMesa = new ClasseVendaMesa();
        }
        vendaMesa.setIdMesa(Integer.valueOf(lbNumMesa.getText()));
        vendaMesa.setTotalVenda(Float.valueOf(txtValorPagar.getText()));
        vendaMesa.setItensMesa(itensMesa);
        vendaMesa.setDataVenda(retornaData());
        vendaMesa.setFormaPagamento((String) cmbFormaPagamento.getModel().getSelectedItem());
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNumMesa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbFormaPagamento = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        txtDesconto = new javax.swing.JTextField();
        txtTaxaServico = new javax.swing.JTextField();
        txtValorPagar = new javax.swing.JTextField();
        txtValorRecebido = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        chkRetiraTaxa = new javax.swing.JCheckBox();
        btPesquisaCliente = new javax.swing.JButton();
        jTNomeCliente = new javax.swing.JTextField();
        btFechaVenda = new javax.swing.JButton();
        btVoltarMesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fechamento da Mesa/ PubManager.Soft");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoSistema2.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(240, 204, 153));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Fechamento Mesa");

        lbNumMesa.setBackground(new java.awt.Color(240, 204, 153));
        lbNumMesa.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbNumMesa.setText("000");

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setBackground(new java.awt.Color(240, 204, 153));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Forma de Pagamento:");

        cmbFormaPagamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbFormaPagamento.setMaximumRowCount(10);
        cmbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DINHEIRO", "CHEQUE", "CARTÃO DE DÉBITO", "CARTÃO DE CRÉDITO", "VOUCHER", "A PRAZO" }));
        cmbFormaPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbFormaPagamentoMouseClicked(evt);
            }
        });
        cmbFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFormaPagamentoActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(240, 204, 153));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("SubTotal R$:");

        jLabel5.setBackground(new java.awt.Color(240, 204, 153));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Desconto R$:");

        jLabel6.setBackground(new java.awt.Color(240, 204, 153));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Taxa de Serviço R$:");

        jLabel7.setBackground(new java.awt.Color(240, 204, 153));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Valor à Pagar R$:");

        jLabel8.setBackground(new java.awt.Color(240, 204, 153));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Recebido R$:");

        jLabel9.setBackground(new java.awt.Color(240, 204, 153));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Troco R$:");

        txtSubTotal.setEditable(false);
        txtSubTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtSubTotal.setText("0.00");

        txtDesconto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDesconto.setText("0.00");
        txtDesconto.setToolTipText("");
        txtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescontoFocusLost(evt);
            }
        });
        txtDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescontoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescontoKeyTyped(evt);
            }
        });

        txtTaxaServico.setEditable(false);
        txtTaxaServico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTaxaServico.setText("0.00");

        txtValorPagar.setEditable(false);
        txtValorPagar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtValorPagar.setText("0.00");

        txtValorRecebido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtValorRecebido.setText("0.00");
        txtValorRecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorRecebidoFocusLost(evt);
            }
        });
        txtValorRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorRecebidoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorRecebidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorRecebidoKeyTyped(evt);
            }
        });

        txtTroco.setEditable(false);
        txtTroco.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTroco.setText("0.00");

        chkRetiraTaxa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chkRetiraTaxa.setText("Remover Taxa");
        chkRetiraTaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRetiraTaxaActionPerformed(evt);
            }
        });

        btPesquisaCliente.setText("Cliente");
        btPesquisaCliente.setEnabled(false);
        btPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaClienteActionPerformed(evt);
            }
        });

        jTNomeCliente.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTNomeCliente)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(110, 110, 110)
                                .addComponent(txtTroco, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtValorRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addComponent(cmbFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(txtTaxaServico, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDesconto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkRetiraTaxa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPesquisaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisaCliente))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(chkRetiraTaxa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jTNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTaxaServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(lbNumMesa)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNumMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btFechaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ok.png"))); // NOI18N
        btFechaVenda.setText("Fechar Venda");
        btFechaVenda.setToolTipText("Fechar a venda e imprimir o cupom fiscal");
        btFechaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechaVendaActionPerformed(evt);
            }
        });

        btVoltarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sair.png"))); // NOI18N
        btVoltarMesa.setText("Voltar");
        btVoltarMesa.setToolTipText("Volta para a tela da mesa");
        btVoltarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btVoltarMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFechaVenda))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltarMesa)
                    .addComponent(btFechaVenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkRetiraTaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRetiraTaxaActionPerformed
        if (cmbFormaPagamento.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma Forma de\nPagamento!",
                    "Fechamento de Venda", JOptionPane.INFORMATION_MESSAGE);
            chkRetiraTaxa.setSelected(false);
        } else {
            if (chkRetiraTaxa.isSelected()) {
                txtTaxaServico.setText("0.00");
                calculaVPagar();
            } else {
                txtTaxaServico.setText(decimal.format(Float.valueOf(txtSubTotal.getText()) * 0.10).replaceAll(",", "."));
                calculaVPagar();
            }
        }
    }//GEN-LAST:event_chkRetiraTaxaActionPerformed

    private void txtDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyTyped
        if (!numeros.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtDescontoKeyTyped

    private void txtValorRecebidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRecebidoKeyTyped
        if (!numeros.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtValorRecebidoKeyTyped

    private void btVoltarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMesaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btVoltarMesaActionPerformed

    private void txtDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyReleased
        txtDesconto.setText(txtDesconto.getText().replaceAll(",", "."));
        calculaVPagar();
    }//GEN-LAST:event_txtDescontoKeyReleased

    private void txtValorRecebidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRecebidoKeyReleased
        if (!txtValorRecebido.getText().equals("")){
            txtValorRecebido.setText(txtValorRecebido.getText().replaceAll(",", "."));
            calculaVPagar();
        }
    }//GEN-LAST:event_txtValorRecebidoKeyReleased

    private void txtValorRecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorRecebidoFocusLost
        if (txtValorRecebido.getText().equals("")){
            txtValorRecebido.setText("0.00");
            calculaVPagar();
        }
    }//GEN-LAST:event_txtValorRecebidoFocusLost

    private void txtDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescontoFocusLost
        if (txtDesconto.getText().equals("")){
            txtDesconto.setText("0.00");
            calculaVPagar();
        }
    }//GEN-LAST:event_txtDescontoFocusLost

    private void txtDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyPressed
        if (evt.getKeyChar() == '.'){
            if (txtDesconto.getText().contains(evt.getKeyChar()+"")){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtDescontoKeyPressed

    private void txtValorRecebidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRecebidoKeyPressed
        if (evt.getKeyChar() == '.'){
            if (txtValorRecebido.getText().contains(evt.getKeyChar()+"")){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtValorRecebidoKeyPressed

    private void btFechaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechaVendaActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja Finalizar a venda?", "PubManager.Soft",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (Float.valueOf(txtValorRecebido.getText()) >= Float.valueOf(txtValorPagar.getText())) {
                preencheClasse();
                if (vendaMesa.cadastraVenda(vendaMesa)) {
                    if(!jTNomeCliente.getText().equals("Cliente nao localizado!")){
                       vendaMesa.cadastrarVendaAprazo(vendaMesa, tbClientes);
                    }else{
                        JOptionPane.showMessageDialog(this, "Informe o cliente",
                            "PubManager.Soft", JOptionPane.INFORMATION_MESSAGE);
                    }
                    JOptionPane.showMessageDialog(this, "Venda Efetuada com Sucesso",
                            "PubManager.Soft", JOptionPane.INFORMATION_MESSAGE);
                    telaPai.setModal(false);
                    this.setModal(false);
                    telaPai.getObjMesa().finalizaMesa();
                    this.setVisible(false);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Não Foi Possivel Realizar a venda!\nErro no Banco de Dados",
                            "PubManager.Soft", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Valor Recebido Menor que o Valor Devido!",
                        "PubManager.Soft", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btFechaVendaActionPerformed

    private void cmbFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFormaPagamentoActionPerformed

    private void btPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaClienteActionPerformed
        PesquisaCliente pCliente = new PesquisaCliente(null, true);
        pCliente.setAlwaysOnTop(true);
        pCliente.setVisible(true);
        int id = tbClientes.buscaIdAuxiliar();
        tbClientes.setIdCliente(id);
        if(tbClientes.buscaCliente(tbClientes)){
            jTNomeCliente.setText(tbClientes.getNome());
        }else{
            jTNomeCliente.setText("Cliente nao localizado!");
        }
        tbClientes.apagarIdAuxiliar();
    }//GEN-LAST:event_btPesquisaClienteActionPerformed

    private void cmbFormaPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbFormaPagamentoMouseClicked

        cmbFormaPagamento.addActionListener( new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(cmbFormaPagamento.getSelectedItem().equals("A PRAZO")){
                    btPesquisaCliente.setEnabled(true);
                }else{
                    btPesquisaCliente.setEnabled(false);
                    jTNomeCliente.setEnabled(false);
                }               
            }
        });  
      
    }//GEN-LAST:event_cmbFormaPagamentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFechaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFechaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFechaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFechaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFechaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechaVenda;
    private javax.swing.JButton btPesquisaCliente;
    private javax.swing.JButton btVoltarMesa;
    private javax.swing.JCheckBox chkRetiraTaxa;
    private javax.swing.JComboBox cmbFormaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTNomeCliente;
    private javax.swing.JLabel lbNumMesa;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTaxaServico;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorPagar;
    private javax.swing.JTextField txtValorRecebido;
    // End of variables declaration//GEN-END:variables
}
